Added stuff
st0ppers/OnlineBookstore pull request #3
Opened 2022-09-30 14:41 UTC by st0ppers

2022-10-01 05:11 UTC, sabazius requested changes

2022-10-01 05:11 UTC, sabazius commented on BookStore/BookStore.BL/Interfaces/IPersonService.cs
> +        public Guid GetGuidId();
това за Guid го махни. Беше само за демонстрация на лайфтайма на сървисите

2022-10-01 05:11 UTC, sabazius commented on BookStore/BookStore.Models/Class1.cs
> +    public class User
Този клас няма да го използваме. И  си забравил името на файла Class1.cs.  Можеш да го изтриеш.

2022-10-01 05:11 UTC, sabazius commented on BookStore/BookStore/BookStore.csproj
> +    <ProjectReference Include="..\OnlineBookstore.DL\OnlineBookstore.DL.csproj" />
UI нивото не трябва да знае за DL. Трябва да ти работи без тази референиця

2022-10-01 05:11 UTC, sabazius commented on BookStore/BookStore/Controllers/AuthorController.cs
> +        private static IAuthorRepo _authorRepo;
В контролерите, използвай само сървиси за достъп до DL

2022-10-01 05:11 UTC, sabazius commented on BookStore/BookStore/Controllers/AuthorController.cs
> +        [HttpGet(nameof(GetGuid))]
Този Guid е излишен

2022-10-01 05:11 UTC, sabazius commented on BookStore/BookStore/Controllers/UserController.cs
> +        private static IUserRepository _userRepo;
и тук трябва да е през сървис

2022-10-01 05:11 UTC, sabazius commented on BookStore/OnlineBookstore.DL/Interface/IAuthorRepo.cs
> +        public Guid Id { get; set; }
няма да ни трябва

2022-10-01 05:11 UTC, sabazius commented on BookStore/OnlineBookstore.DL/Interface/IPersonRepo.cs
> +        public Guid Id { get; set; }
и това

2022-10-01 05:11 UTC, sabazius commented on BookStore/OnlineBookstore.DL/Repositories/InMemoryRepositories/AuthorRepo.cs
> +        public Guid Id { get; set; }
и това можеш да махнеш

2022-10-01 05:11 UTC, sabazius commented on BookStore/OnlineBookstore.DL/Repositories/InMemoryRepositories/PersonRepo.cs
> +            throw new NotImplementedException();
неимплеменирани методи не трябва да има

2022-10-01 15:53 UTC, st0ppers commented on BookStore/BookStore/Controllers/AuthorController.cs
> +        private static IAuthorRepo _authorRepo;
По време на лекция не ми остана време да ги променя. Сега в нас ще го довърша

2022-10-01 16:06 UTC, st0ppers commented on BookStore/BookStore.Models/Class1.cs
> +    public class User
Оставих го за да мога вкъщи да се упражнявам и на него да направя services. Понеделник ще го изтрия ако тогава не е проблем

2022-10-02 06:32 UTC, sabazius commented on BookStore/BookStore.Models/Class1.cs
> +    public class User
Можеш да си направиш бранч и да се упражняваш в него. Така ще си действаш и като работиш в някой екип. Пул рикуестите и мейн бранча отива само код, който е работещ, тестван и изчистен от излишни работи. Направи си бранч от този и в него ще имаш същите неща. После изтрий от тук и пусни нов пул рикуест.

2022-10-02 12:56 UTC, merged